[project]
authors = ["cgeady <caryn@geady.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "simulations"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
pip = ">=25.0.1,<26"
ipykernel = ">=6.29.5,<7"
numpy = ">=2.2.3,<3"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
stats = ">=0.1.2a0, <0.2"
